local lottery_const = {
    GAME_JSSSC_BETTING = {},        -- 极速时时彩投注
    GAME_JSSSC_ODDS = {},           -- 极速时时彩赔率
    GAME_JSSSC_ONE_ISSUE_TIME_SPAN = 75,
    GAME_JSSSC_OPENING_TIME_SPAN = 60,
    GAME_JSSSC_SEALING_TIME_SPAN = 15,
    LOCK_STATE = {
        NO = "NO",
        YES = "YES"
    },
    GAME_STATE = {
        OPENING = "OPENING",
        SEALING = "SEALING"
    }
}

-- ========================================极速时时彩========================================
lottery_const.GAME_JSSSC_BETTING.BETTING_MODULE = {
    SINGLE_BALL_1_VALUE = "SINGLE_BALL_1_VALUE",
    SINGLE_BALL_1_FACE = "SINGLE_BALL_1_FACE",
    SINGLE_BALL_1_SIZE = "SINGLE_BALL_1_SIZE",
    SINGLE_BALL_2_VALUE = "SINGLE_BALL_2_VALUE",
    SINGLE_BALL_2_FACE = "SINGLE_BALL_2_FACE",
    SINGLE_BALL_2_SIZE = "SINGLE_BALL_2_SIZE",
    SINGLE_BALL_3_VALUE = "SINGLE_BALL_3_VALUE",
    SINGLE_BALL_3_FACE = "SINGLE_BALL_3_FACE",
    SINGLE_BALL_3_SIZE = "SINGLE_BALL_3_SIZE",
    SINGLE_BALL_4_VALUE = "SINGLE_BALL_4_VALUE",
    SINGLE_BALL_4_FACE = "SINGLE_BALL_4_FACE",
    SINGLE_BALL_4_SIZE = "SINGLE_BALL_4_SIZE",
    SINGLE_BALL_5_VALUE = "SINGLE_BALL_5_VALUE",
    SINGLE_BALL_5_FACE = "SINGLE_BALL_5_FACE",
    SINGLE_BALL_5_SIZE = "SINGLE_BALL_5_SIZE",
    SUM_BALL_FACE = "SUM_BALL_FACE",
    SUM_BALL_SIZE = "SUM_BALL_SIZE",
    FIRST_THREE_BALL = "FIRST_THREE_BALL",
    MIDDLE_THREE_BALL = "MIDDLE_THREE_BALL",
    LAST_THREE_BALL = "LAST_THREE_BALL",
    DRAGON_TIGER_TIE = "DRAGON_TIGER_TIE"
}
lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY = {
    NUMBER0 = "NUMBER0",
    NUMBER1 = "NUMBER1",
    NUMBER2 = "NUMBER2",
    NUMBER3 = "NUMBER3",
    NUMBER4 = "NUMBER4",
    NUMBER5 = "NUMBER5",
    NUMBER6 = "NUMBER6",
    NUMBER7 = "NUMBER7",
    NUMBER8 = "NUMBER8",
    NUMBER9 = "NIMBER9"
}
lottery_const.GAME_JSSSC_BETTING.BETTING_FACE_PLAY = {
    SINGLE = "SINGLE",                  -- 单
    DOUBLE = "DOUBLE"                   -- 双
}
lottery_const.GAME_JSSSC_BETTING.BETTING_SIZE_PLAY = {
    LARGE = "LARGE",                    -- 大
    SMALL = "SMALL"                     -- 小
}
lottery_const.GAME_JSSSC_BETTING.BETTING_THREE_BALL_PLAY = {
    LEOPARD = "LEOPARD",                -- 豹子
    STRAIGHT = "STRAIGHT",              -- 顺子
    COUPLET = "COUPLET",                -- 对子
    SEMI_STRAIGHT = "SEMI_STRAIGHT",    -- 半顺
    DISORDER = "DISORDER"               -- 杂六
}
lottery_const.GAME_JSSSC_BETTING.BETTING_DRAGON_TIGER_TIE_PLAY = {
    DRAGON = "DRAGON",                  -- 龙
    TIGER = "TIGER",                    -- 虎
    TIE = "TIE"                         -- 和
}
lottery_const.GAME_JSSSC_ODDS[lottery_const.GAME_JSSSC_BETTING.BETTING_MODULE.SINGLE_BALL_1_VALUE] = {
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER0] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER1] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER2] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER3] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER4] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER5] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER6] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER7] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER8] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER9] = 9.933
}
lottery_const.GAME_JSSSC_ODDS[lottery_const.GAME_JSSSC_BETTING.BETTING_MODULE.SINGLE_BALL_1_FACE] = {
    [lottery_const.GAME_JSSSC_BETTING.BETTING_FACE_PLAY.SINGLE] = 1.9868,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_FACE_PLAY.DOUBLE] = 1.9868
}
lottery_const.GAME_JSSSC_ODDS[lottery_const.GAME_JSSSC_BETTING.BETTING_MODULE.SINGLE_BALL_1_SIZE] = {
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SIZE_PLAY.LARGE] = 1.9868,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SIZE_PLAY.SMALL] = 1.9868
}
lottery_const.GAME_JSSSC_ODDS[lottery_const.GAME_JSSSC_BETTING.BETTING_MODULE.SINGLE_BALL_2_VALUE] = {
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER0] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER1] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER2] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER3] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER4] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER5] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER6] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER7] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER8] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER9] = 9.933
}
lottery_const.GAME_JSSSC_ODDS[lottery_const.GAME_JSSSC_BETTING.BETTING_MODULE.SINGLE_BALL_2_FACE] = {
    [lottery_const.GAME_JSSSC_BETTING.BETTING_FACE_PLAY.SINGLE] = 1.9868,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_FACE_PLAY.DOUBLE] = 1.9868
}
lottery_const.GAME_JSSSC_ODDS[lottery_const.GAME_JSSSC_BETTING.BETTING_MODULE.SINGLE_BALL_2_SIZE] = {
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SIZE_PLAY.LARGE] = 1.9868,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SIZE_PLAY.SMALL] = 1.9868
}
lottery_const.GAME_JSSSC_ODDS[lottery_const.GAME_JSSSC_BETTING.BETTING_MODULE.SINGLE_BALL_3_VALUE] = {
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER0] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER1] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER2] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER3] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER4] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER5] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER6] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER7] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER8] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER9] = 9.933
}
lottery_const.GAME_JSSSC_ODDS[lottery_const.GAME_JSSSC_BETTING.BETTING_MODULE.SINGLE_BALL_3_FACE] = {
    [lottery_const.GAME_JSSSC_BETTING.BETTING_FACE_PLAY.SINGLE] = 1.9868,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_FACE_PLAY.DOUBLE] = 1.9868
}
lottery_const.GAME_JSSSC_ODDS[lottery_const.GAME_JSSSC_BETTING.BETTING_MODULE.SINGLE_BALL_3_SIZE] = {
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SIZE_PLAY.LARGE] = 1.9868,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SIZE_PLAY.SMALL] = 1.9868
}
lottery_const.GAME_JSSSC_ODDS[lottery_const.GAME_JSSSC_BETTING.BETTING_MODULE.SINGLE_BALL_4_VALUE] = {
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER0] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER1] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER2] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER3] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER4] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER5] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER6] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER7] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER8] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER9] = 9.933
}
lottery_const.GAME_JSSSC_ODDS[lottery_const.GAME_JSSSC_BETTING.BETTING_MODULE.SINGLE_BALL_3_FACE] = {
    [lottery_const.GAME_JSSSC_BETTING.BETTING_FACE_PLAY.SINGLE] = 1.9868,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_FACE_PLAY.DOUBLE] = 1.9868
}
lottery_const.GAME_JSSSC_ODDS[lottery_const.GAME_JSSSC_BETTING.BETTING_MODULE.SINGLE_BALL_3_SIZE] = {
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SIZE_PLAY.LARGE] = 1.9868,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SIZE_PLAY.SMALL] = 1.9868
}
lottery_const.GAME_JSSSC_ODDS[lottery_const.GAME_JSSSC_BETTING.BETTING_MODULE.SINGLE_BALL_5_VALUE] = {
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER0] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER1] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER2] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER3] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER4] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER5] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER6] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER7] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER8] = 9.933,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SINGLE_BALL_VALUE_PLAY.NUMBER9] = 9.933
}
lottery_const.GAME_JSSSC_ODDS[lottery_const.GAME_JSSSC_BETTING.BETTING_MODULE.SINGLE_BALL_5_FACE] = {
    [lottery_const.GAME_JSSSC_BETTING.BETTING_FACE_PLAY.SINGLE] = 1.9868,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_FACE_PLAY.DOUBLE] = 1.9868
}
lottery_const.GAME_JSSSC_ODDS[lottery_const.GAME_JSSSC_BETTING.BETTING_MODULE.SINGLE_BALL_5_SIZE] = {
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SIZE_PLAY.LARGE] = 1.9868,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SIZE_PLAY.SMALL] = 1.9868
}
lottery_const.GAME_JSSSC_ODDS[lottery_const.GAME_JSSSC_BETTING.BETTING_MODULE.SUM_BALL_FACE] = {
    [lottery_const.GAME_JSSSC_BETTING.BETTING_FACE_PLAY.SINGLE] = 1.9868,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_FACE_PLAY.DOUBLE] = 1.9868
}
lottery_const.GAME_JSSSC_ODDS[lottery_const.GAME_JSSSC_BETTING.BETTING_MODULE.SUM_BALL_SIZE] = {
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SIZE_PLAY.LARGE] = 1.9868,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_SIZE_PLAY.SMALL] = 1.9868
}
lottery_const.GAME_JSSSC_ODDS[lottery_const.GAME_JSSSC_BETTING.BETTING_MODULE.FIRST_THREE_BALL] = {
    [lottery_const.GAME_JSSSC_BETTING.BETTING_THREE_BALL_PLAY.LEOPARD] = 69,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_THREE_BALL_PLAY.STRAIGHT] = 12.902,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_THREE_BALL_PLAY.COUPLET] = 2.7,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_THREE_BALL_PLAY.SEMI_STRAIGHT] = 2.1,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_THREE_BALL_PLAY.DISORDER] = 2.4
}
lottery_const.GAME_JSSSC_ODDS[lottery_const.GAME_JSSSC_BETTING.BETTING_MODULE.MIDDLE_THREE_BALL] = {
    [lottery_const.GAME_JSSSC_BETTING.BETTING_THREE_BALL_PLAY.LEOPARD] = 69,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_THREE_BALL_PLAY.STRAIGHT] = 12.902,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_THREE_BALL_PLAY.COUPLET] = 2.7,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_THREE_BALL_PLAY.SEMI_STRAIGHT] = 2.1,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_THREE_BALL_PLAY.DISORDER] = 2.4
}
lottery_const.GAME_JSSSC_ODDS[lottery_const.GAME_JSSSC_BETTING.BETTING_MODULE.LAST_THREE_BALL] = {
    [lottery_const.GAME_JSSSC_BETTING.BETTING_THREE_BALL_PLAY.LEOPARD] = 69,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_THREE_BALL_PLAY.STRAIGHT] = 12.902,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_THREE_BALL_PLAY.COUPLET] = 2.7,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_THREE_BALL_PLAY.SEMI_STRAIGHT] = 2.1,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_THREE_BALL_PLAY.DISORDER] = 2.4
}
lottery_const.GAME_JSSSC_ODDS[lottery_const.GAME_JSSSC_BETTING.BETTING_MODULE.DRAGON_TIGER_TIE] = {
    [lottery_const.GAME_JSSSC_BETTING.BETTING_DRAGON_TIGER_TIE_PLAY.DRAGON] = 1.9868,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_DRAGON_TIGER_TIE_PLAY.TIGER] = 1.9868,
    [lottery_const.GAME_JSSSC_BETTING.BETTING_DRAGON_TIGER_TIE_PLAY.TIE] = 8.9,
}
-- ========================================================================================


return lottery_const